### ISSUE TITLE
Clean up the code

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/ckanext-datopian#2]
@obanlatomiwa is there any reason you have committed `__pycache__` directories? Those must not be committed and should be in `.gitignore`. 

Also, what is the reason of copying every single template file from CKAN core?

**Comment by anuveyatsu** [comment]
@obanlatomiwa could you check if this is fixed already?

**Comment by obanlatomiwa** [comment]
@anuveyatsu do you mean if the extension is working?

**Comment by anuveyatsu** [comment]
@obanlatomiwa I mean this particular issue about cleaning up

**Comment by obanlatomiwa** [comment]
I have removed `__pycache__`.
At the time when I created the extension, I didn't know what file would be modified that's why I copied ckan template for extensions.

**Comment by obanlatomiwa** [comment]
For cleaning up, @tanvirchahal will have to help in identifying what files he modified. Then I can remove the rest.

**Comment by anuveyatsu** [comment]
Closing as FIXED as no further progress needed.
